### ISSUE TITLE
Github workflow use GITHUB_REPOSITORY environment-variables

### ISSUE THREAD

**Issue by maguowei** [maguowei/awesome-stars#1]
`--username maguowei --repository awesome-stars` -> `--repository ${GITHUB_REPOSITORY}`

ref: https://help.github.com/en/articles/virtual-environments-for-github-actions#environment-variables

**Comment by laur89** [comment]
secrets starting with `GITHUB` are no longer allowed; this should be renamed in readme & https://github.com/maguowei/awesome-stars/blob/master/.github/workflows/schedules.yml
